import Head from 'next/head'
import Navbar from '@/componants/Navbar'
import Intro from '@/componants/Intro'
import { TabList, Tabs, useColorMode } from '@chakra-ui/react'
import Footer from '@/componants/Footer'
import Commandp from '@/componants/Commandp'
import Admin from '@/componants/Admin'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/router'




export default function AdminPage({data}) {

    const { colorMode, toggleColorMode } = useColorMode();
    const { data: session, status } = useSession();
    const router = useRouter();
    if (session !== null) {
        return (
            <>
                <Head>
                    <title>Asif Ekbal</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="public/asif.png" />
                </Head>
                <main
                >
                    <Commandp>
                        <Navbar />

                        <Admin data={data} />


                        <Footer />
                    </Commandp>
                </main>
            </>
        )

    } else {
        router.push('/')

    }



}
export async function getStaticProps() {
    const res = await fetch("http://localhost:3000/api/projects?id=" + 4356786, {
        method: "GET",
    });
    const data = await res.json();
   
    return {
        props: {
            data,
        },
    }
}

