import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/componants/Navbar'
import Intro from '@/componants/Intro'
import { allwork, recentwork } from '@/data/data'
import Works from '@/componants/Works'
import { useColorMode } from '@chakra-ui/react'
import With from '@/componants/With'
import Footer from '@/componants/Footer'
import Commandp from '@/componants/Commandp'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <>
      <Head>
        <title>Asif Ekbal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="public/asif.png" />
      </Head>
      <main>
        <Commandp>
          <Navbar />
          <Intro />
          <Works
            data={recentwork}
            title="Recent Work"
            desc="My recent projects"
            _bg={colorMode === "light" ? "blackAlpha.100" : "#0e1013"}
          />
          <Works
            data={allwork}
            title="All Works"
            desc=""
            _bg={colorMode === "light" ? "white" : "#17181b"}
          />
          <With />
          <Footer />
        </Commandp>

      </main>
    </>
  )
}
